module.exports = {
  NAME: 'Plenty Defi',
  API: {
    url: 'https://api.coingecko.com/api/v3/coins/tezos?localization=false&tickers=false&community_data=false&developer_data=false&sparkline=false',
    API_KEY: '4824FE50-DB6E-4316-B099-72283C964891',
  },
  RPC_NODES: {
    testnet: 'https://testnet-tezos.giganode.io/',
    mainnet: 'https://mainnet-tezos.giganode.io/',
  },
  TZKT_NODES: {
    mainnet: 'https://api.tzkt.io',
    testnet: 'https://api.florencenet.tzkt.io',
  },
  AMM: {
    testnet: {
      PLENTY: {
        ICON: '',
        TOKEN_CONTRACT: 'KT1TbkspJ8AzLmNs3ko9xr46ZE4zLpyZu9tX',
        READ_TYPE: 'FA1.2',
        CALL_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 18,
        DEX_PAIRS: {
          wDAI: '',
          KALAM: '',
          WRAP: {
            contract: 'KT1HePFs4aA5u6A5BDw3ot7LuXvqa4ebqrTQ',
            property: 'token2_pool',
          },
        },
      },
      WRAP: {
        ICON: '',
        TOKEN_CONTRACT: 'KT1L1xYJit22TmuhDXaeng4AZDhRqZwcacNj',
        READ_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 8,
        DEX_PAIRS: {
          wDAI: {
            contract: 'KT1PnFKMA2v1ngvYUh5UKtaDuM5WxskrunFm',
            property: 'token1_pool',
          },
          PLENTY: {
            contract: 'KT1HePFs4aA5u6A5BDw3ot7LuXvqa4ebqrTQ',
            property: 'token1_pool',
          },
          KALAM: '',
        },
      },
      wDAI: {
        ICON: '',
        TOKEN_CONTRACT: 'KT1DJwRryZ11dGDnqmmRtTiSsgxQDY4bw3j4',
        READ_TYPE: 'FA2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 18,
        DEX_PAIRS: {
          PLENTY: '',
          KALAM: '',
          WRAP: {
            contract: 'KT1PnFKMA2v1ngvYUh5UKtaDuM5WxskrunFm',
            property: 'token2_pool',
          },
        },
      },
      KALAM: {
        ICON: '',
        TOKEN_CONTRACT: 'KT1GwebtXvQsFBcYzVAbMuafAk3DW8LD3M6q',
        READ_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 10,
        DEX_PAIRS: {
          PLENTY: '',
          wDAI: '',
          WRAP: '',
        },
      },
    },
  },
  CONTRACT: {
    testnet: {
      POOLS: {
        PLENTY: {
          TOKEN: 'KT1JCq5sWnE8EivqhY7RuNSHgC5injKYLUCT',
          CONTRACT: 'KT1RA4WgHFCP33WTV1QiBeNebimxS57kbcV7',
          DEX: 'KT1SVjwMhHjokd6iJY6XZAk6p1T1hfuNYHkr',
          TYPE: 'FA1.2',
          TOKEN_DECIMAL: 18,
        },
        wBUSD: {
          TOKEN: 'KT1E9sVkhpWTArYktCT2y6HYXMQvttzrpG9t',
          CONTRACT: 'KT1EMet7icBnyfD6WDPKAizF4sFNEmKPJcfq',
          DEX: 'KT1MxGmZ9UWourzGPmvXNuVLHZzr1ecjTYzU',
          TYPE: 'FA1.2',
          TOKEN_DECIMAL: 18,
        },
        ETHtz: {
          TOKEN: 'KT1DJwRryZ11dGDnqmmRtTiSsgxQDY4bw3j4',
          CONTRACT: 'KT1P2sbrXteRQDxLwzUTtPoUw71DxH1EEnGz',
          DEX: 'KT1FkFC5ovz9UrGoQJLd5hyjmz6aSnASTDsx',
          TYPE: 'FA2',
          TOKEN_DECIMAL: 18,
          TOKEN_ID: 0,
        },
      },
      FARMS: {
        'PLENTY - XTZ': {
          LP_TOKEN: 'KT1SVjwMhHjokd6iJY6XZAk6p1T1hfuNYHkr',
          CONTRACT: 'KT1R3WLa7QsDvNLScGTKhAV1PDWHZcQzVUsZ',
          DEX: 'KT1SVjwMhHjokd6iJY6XZAk6p1T1hfuNYHkr',
          TOKEN_DECIMAL: 18,
        },
      },
      LOCKERS: {
        KALAM: {
          REWARD_TOKEN: 'KT1GwebtXvQsFBcYzVAbMuafAk3DW8LD3M6q',
          STAKING_TOKEN: 'KT1TbkspJ8AzLmNs3ko9xr46ZE4zLpyZu9tX',
          STAKING_CONTRACT: 'KT1RNAw46G2nDZB78CCs2CWVuoW5TQc9jUE4',
          STAKING_TOKEN_DEX: 'KT1SVjwMhHjokd6iJY6XZAk6p1T1hfuNYHkr',
          REWARD_TOKEN_DEX: 'KT1X3DzpHDFYbtPyLUtb9GuM7fLezQrg6LcA',
          STAKING_TOKEN_DECIMAL: 18,
          REWARD_TOKEN_DECIMAL: 10,
          TYPE: 'FA1.2',
        },
      },
    },
    mainnet: {
      POOLS: {
        PLENTY: {
          TOKEN: 'KT1GRSvLoikDsXujKgZPsGLX8k8VvR2Tq95b',
          CONTRACT: 'KT1QqjR4Fj9YegB37PQEqXUPHmFbhz6VJtwE',
          DEX: 'KT1X1LgNkQShpF9nRLYw3Dgdy4qp38MX617z',
          INACTIVE: 'KT1UDe1YP963CQSb5xN7cQ1X8NJ2pUyjGw5T',
          TYPE: 'FA1.2',
          TOKEN_DECIMAL: 18,
          TOKEN_ID: 0,
          DECIMAL: 18,
        },
        wMATIC: {
          TOKEN: 'KT18fp5rcTW7mbWDmzFwjLDUhs5MeJmagDSZ',
          CONTRACT: 'KT1XherecVvrE6X4PV5RTwdEKNzA294ZE9T9',
          DEX: 'KT1RsfuBee5o7GtYrdB7bzQ1M6oVgyBnxY4S',
          INACTIVE: 'KT1TNzH1KiVsWh9kpFrWACrDNnfK4ihvGAZs',
          TYPE: 'FA2',
          TOKEN_DECIMAL: 18,
          TOKEN_ID: 11,
          DECIMAL: 18,
        },
        wLINK: {
          TOKEN: 'KT18fp5rcTW7mbWDmzFwjLDUhs5MeJmagDSZ',
          CONTRACT: 'KT1KyxPitU1xNbTriondmAFtPEcFhjSLV1hz',
          DEX: 'KT1Lpysr4nzcFegC9ci9kjoqVidwoanEmJWt',
          INACTIVE: 'KT1JCkdS3x5hTWdrTQdzK6vEkeAdQzsm2wzf',
          TYPE: 'FA2',
          TOKEN_DECIMAL: 18,
          TOKEN_ID: 10,
          DECIMAL: 18,
        },
        USDtz: {
          TOKEN: 'KT1LN4LPSqTMS7Sd2CJw4bbDGRkMv2t68Fy9',
          CONTRACT: 'KT1MBqc3GHpApBXaBZyvY63LF6eoFyTWtySn',
          DEX: 'KT1WxgZ1ZSfMgmsSDDcUn8Xn577HwnQ7e1Lb',
          INACTIVE: 'KT1K5cgrw1A8WTiizZ5b6TxNdFnBq9AtyQ7X',
          TYPE: 'FA1.2',
          TOKEN_DECIMAL: 6,
          TOKEN_ID: 0,
          DECIMAL: 18,
        },
        ETHtz: {
          TOKEN: 'KT19at7rQUvyjxnZ2fBv7D9zc8rkyG7gAoU8',
          CONTRACT: 'KT19asUVzBNidHgTHp8MP31YSphooMb3piWR',
          DEX: 'KT1Evsp2yA19Whm24khvFPcwimK6UaAJu8Zo',
          INACTIVE: 'KT1J7v85udA8GnaBupacgY9mMvrb8zQdYb3E',
          TYPE: 'FA1.2',
          TOKEN_DECIMAL: 18,
          TOKEN_ID: 0,
          DECIMAL: 18,
        },
        hDAO: {
          TOKEN: 'KT1AFA2mwNUMNd4SsujE1YYp29vd8BZejyKW',
          CONTRACT: 'KT1Ga15wxGR5oWK1vBG2GXbjYM6WqPgpfRSP',
          DEX: 'KT1QxLqukyfohPV5kPkw97Rs6cw1DDDvYgbB',
          INACTIVE: 'KT1Vs8gqh7YskPnUQMfmjogZh3A5ZLpqQGcg',
          TYPE: 'FA2',
          TOKEN_DECIMAL: 6,
          TOKEN_ID: 0,
          DECIMAL: 18,
        },
      },
      FARMS: {
        'PLENTY - XTZ': {
          LP_TOKEN: 'KT1X1LgNkQShpF9nRLYw3Dgdy4qp38MX617z',
          CONTRACT: 'KT1JQAZqShNMakSNXc2cgTzdAWZFemGcU6n1',
          DEX: 'KT1X1LgNkQShpF9nRLYw3Dgdy4qp38MX617z',
          INACTIVE: 'KT1BfQLAsQNX8BjSBzgjTLx3GTd3qhwLoWNz',
          TOKEN_ADDRESS: 'KT1GRSvLoikDsXujKgZPsGLX8k8VvR2Tq95b',
          TOKEN_DECIMAL: 6,
          TYPE: 'FA1.2',
          LP_DECIMAL: 18,
          TEMP_ADDRESS: 'KT1GRSvLoikDsXujKgZPsGLX8k8VvR2Tq95b',
          DECIMAL: 18,
        },
        'KALAM - XTZ': {
          LP_TOKEN: 'KT1J3wTYb4xk5BsSBkg6ML55bX1xq7desS34',
          CONTRACT: '',
          DEX: 'KT1J3wTYb4xk5BsSBkg6ML55bX1xq7desS34',
          INACTIVE: 'KT1DjDZio7k2GJwCJCXwK82ing3n51AE55DW',
          TOKEN_ADDRESS: 'KT1GRSvLoikDsXujKgZPsGLX8k8VvR2Tq95b',
          TOKEN_DECIMAL: 6,
          TYPE: 'FA2',
          TOKEN_ID: 0,
          LP_DECIMAL: 12,
          TEMP_ADDRESS: 'KT1A5P4ejnLix13jtadsfV9GCnXLMNnab8UT',
          DECIMAL: 18,
        },
      },
      LOCKERS: {
        KALAM: {
          REWARD_TOKEN: 'KT1A5P4ejnLix13jtadsfV9GCnXLMNnab8UT',
          STAKING_TOKEN: 'KT1GRSvLoikDsXujKgZPsGLX8k8VvR2Tq95b',
          STAKING_CONTRACT: 'KT1WfLprabHVTnNhWFigmopAduUpxG5HKvNf',
          STAKING_TOKEN_DEX: 'KT1X1LgNkQShpF9nRLYw3Dgdy4qp38MX617z',
          REWARD_TOKEN_DEX: 'KT1J3wTYb4xk5BsSBkg6ML55bX1xq7desS34',
          STAKING_TOKEN_DECIMAL: 18,
          REWARD_TOKEN_DECIMAL: 10,
          STAKE_TOKEN: 'PLENTY',
          TYPE: 'FA1.2',
        },
      },
    },
  },
  withdrawalFeeDistribution: {
    testnet: [
      { block: 4096, rate: 25 },
      { block: 8192, rate: 12.5 },
      { block: 12288, rate: 7.5 },
      { block: 16384, rate: 2.5 },
    ],
    mainnet: [],
  },
  NETWORK: 'testnet',
  WALLET_NETWORK: 'florencenet',
  ADMIN_ADDRESS: 'KT1GpTEq4p2XZ8w9p5xM7Wayyw5VR7tb3UaW',
  BURNER: 'tz1ZnK6zYJrC9PfKCPryg9tPW6LrERisTGtg',
};
